apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: mnidevops/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080

---
#NodePort Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  selector:
    name: springboot
  ports:
  - port: 8080
    targetPort: 8080

---
#Mongo Host Path RC
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
      name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
      volumeMount:
      - name: mongo-persistent-storage
        mounthPath: /data/db
    volume:
    - name: mongo-persistent-storage
      hostPath:
        path: /tmp/dbbackup
        

---
#Mongo Cluster IP Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  selector:
    name: mongo
  ports:
  - port: 27017
    targetPort: 27017
